FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

CMD ["python", "app.py"]

FROM python:3.12-slim

WORKDIR /app

# Instalar librerías de pruebas y métricas
RUN pip install --no-cache-dir pytest pytest-cov radon

COPY . .

CMD ["python", "app.py"]